# ==========================================
# 1. USERS MIGRATION JOB
# ==========================================
apiVersion: batch/v1
kind: Job
metadata:
  name: users-migration-job
  namespace: saga-system
spec:
  backoffLimit: 5 # Даем 5 попыток, если БД еще не успела подняться
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: users-migrator
          image: anna13nechytailenko/saga-users:v1.1
          imagePullPolicy: Always
          args: ["migrate"] # Тот самый волшебный триггер
          envFrom:
            - configMapRef:
                name: app-config

---
# ==========================================
# 2. MEETUPS MIGRATION JOB
# ==========================================
apiVersion: batch/v1
kind: Job
metadata:
  name: meetups-migration-job
  namespace: saga-system
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: meetups-migrator
          image: anna13nechytailenko/saga-meetups:v1.1
          imagePullPolicy: Always
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: app-config

---
# ==========================================
# 3. NOTIFICATIONS MIGRATION JOB
# ==========================================
apiVersion: batch/v1
kind: Job
metadata:
  name: notifications-migration-job
  namespace: saga-system
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: notifications-migrator
          image: anna13nechytailenko/saga-notifications:v1.1
          imagePullPolicy: Always
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: app-config

---
# ==========================================
# 4. WORKFLOW MIGRATION JOB
# ==========================================
apiVersion: batch/v1
kind: Job
metadata:
  name: workflow-migration-job
  namespace: saga-system
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: workflow-migrator
          image: anna13nechytailenko/saga-workflow:v1.1
          imagePullPolicy: Always
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: app-config