services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 5

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations
      - -database=${DOCKER_DATABASE_URL}
      - up
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  pgdata:

    # In future do not forget about git commit hash
    # Example : 
    # services:
    #     build:
    #       context: .
    #       dockerfile: deploy/users.Dockerfile
    #       args:
    #         COMMIT_HASH: ${GIT_COMMIT:-unknown} 
